#!/usr/local/bin/python3
import sys
from flask   import Flask
from musicpd import MPDClient
sys.path.insert(0, '/usr/local/var/www/beatbot')
app = Flask(__name__)
app.config.from_object('config')

client = MPDClient()
client.connect(app.config['MPD_ADDRESS'], app.config['MPD_PORT'])

status = client.status()

if int(status['song']) == (int(status['playlistlength']) - 1):
    client.shuffle()

client.close()
client.disconnect()

sys.exit(0)
